hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 15
deployment:
  desiredReplicas: 2
  imageURL: 339712874850.dkr.ecr.us-east-1.amazonaws.com/expense/dev/frontend
  imageVersion: v1
service:
  # type: LoadBalancer
  port: 8080
  targetPort: 8080
  # nodePort: 30011
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:339712874850:targetgroup/expense-dev/684dbc2eb0f40e32